# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file: /gitlab-templates/website-hugo.yml

hugo_website:
  variables:
    KDECI_CACHE_PATH: /mnt/artifacts/suse-qt6.8/
    KDECI_GITLAB_SERVER: https://invent.kde.org/
    KDECI_PACKAGE_PROJECT: teams/ci-artifacts/suse-qt6.8
  # BEGIN OF WORKAROUND
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
    - git clone https://invent.kde.org/sysadmin/ci-notary-service.git
    # workaround: remove broken translations which break the build
    - rm po/sv/kirigami-tutorial.po
    - rm po/ca/kirigami-tutorial.po
    - rm po/sl/kirigami-tutorial.po
    - rm po/nl/kirigami-tutorial.po
    - rm po/uk/kirigami-tutorial.po
  # END OF WORKAROUND

# broken
#html_test:
#  image: invent-registry.kde.org/sysadmin/ci-images/staticweb:latest
#  tags:
#    - Linux
#  stage: test
#  script: htmltest
#  cache:
#    key: htmltest-cache
#    paths:
#      - .htmltest/refcache.json
#    when: always
#  artifacts:
#    name: htmltest_log
#    paths:
#      - .htmltest/htmltest.log
#    when: always
