DirectoryPath: public/ # Directory to scan for HTML files.
IgnoreURLs: # Array of regexs of URLs to ignore.
- https?://.*linkedin.com.*
- https?://.*01.org.*
- https?://.*play.google.com.*
- https?://.*files.kde.org.*
- https?://.*websvn.kde.org.*
- .*livereload.js.*
- /-/.*
IgnoreDirs: # Array of regexs of directories to ignore when scanning for HTML files.
- ^aether/
- ^content/
- ^css/
- ^docs/plasma/widget/snippet/
- ^favicons/
- ^fonts/
- ^kirigami/
- ^images/
- ^js/
- ^media/
- ^resources/
- ^reusable-assets/
- ^scss/
- ^store_badges/
- ^ca/
- ^cs/
- ^de/
- ^eo/
- ^es/
- ^eu/
- ^fi/
- ^fr/
- ^it/
- ^ja/
- ^ko/
- ^lt/
- ^nl/
- ^pl/
- ^pt/
- ^pt-br/
- ^pt-pt/
- ^sk/
- ^sl/
- ^sv/
- ^tr/
- ^uk/
- ^zh-cn/
- ^zh-tw/
# EnforceHTTPS: false # Use this only locally
TestFilesConcurrently: true
IgnoreInternalEmptyHash: true # When true prevents raising an error for links with href="#".
IgnoreExternalBrokenLinks: true # When true produces a warning, rather than an error, for broken external links. Useful when testing a site having hundreds of external links.
IgnoreAltMissing: true # Turns off image alt attribute checking.
IgnoreAltEmpty: true # Allows alt="" for decorative images.
CheckInternal: false # For broken API links
CheckInternalHash: false # For broken API links
IgnoreEmptyHref: true # For broken API links
IgnoreDirectoryMissingTrailingSlash: true # Turns off errors for links to directories without a trailing slash.
IgnoreSSLVerify: true # Turns off x509 errors for self-signed certificates.
#IgnoreTagAttribute: "data-proofer-ignore" # Specify the ignore attribute. All tags with this attribute will be excluded from every check.
#LogLevel: 2 # Logging level, 0-3: debug, info, warning, error.
StripQueryString: true # Enables stripping of query strings from external checks.
#StripQueryExcludes: ["fonts.googleapis.com"] # List of URLs to disable query stripping on.
OutputDir: .htmltest # Directory to store cache and log files in. Relative to executing directory.
OutputCacheFile: refcache.json # File within OutputDir to store reference cache.
OutputLogFile: htmltest.log # File within OutputDir to store last tests errors.
#CacheExpires: 336h (two weeks) # Cache validity period, accepts go.time duration strings (…"m", "h").
