# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Options:
  per-test-timeout: 15:00
  setup-x-environment: False
  setup-dbus-session: False
  run-cppcheck: False
  run-gcovr: False

